steps:
  - label: ':hammer: Build'
    command:
      - "yarn install"
      - "yarn build"
      - "rm -R node_modules"
    plugins:
      - docker#v3.5.0:
          image: "node:12"
          workdir: /app

  - wait 

  - label: ':eslint: Linting'
    command:
      - "yarn lint"
    plugins:
      - docker#v3.5.0:
          image: "node:12"
          workdir: /app

