steps:
  - label: ':hammer: Build'
    command:
      - "yarn install --ignore-scripts"
      - "yarn build"
    plugins:
      - docker#v3.5.0:
          user: 993
          image: "node:12"

  - label: ':eslint: Linting'
    command:
      - "yarn lint"
    plugins:
      - docker#v3.5.0:
          user: 993
          image: "node:12"

