steps:
  - label: ':hammer: Build'
    command:
      - "yarn install"
      - "yarn build"
    plugins:
      - docker#v3.5.0:
          image: "node:12"
          user: 993

  - label: ':eslint: Linting'
    command:
      - "yarn install"
      - "yarn lint"
    plugins:
      - docker#v3.5.0:
          image: "node:12"
          user: 993

