name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 🖥️ Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: 🧶 Install
      run: yarn install
    - name: Copy config
      run: cp config.sample.json config.json
    - name: 🔨 Build
      run: yarn build
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 🖥️ Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: 🧶 Install
      run: yarn install
    - name: 📇 Lint
      run: yarn lint
